### PR TITLE
Catching promise rejection on localStorage access

### PR DESCRIPTION
**Pull request by corrupt**
On some sites the getLocalStorage promise rejects for me, stopping the whole collection process. Most of the times we're interested in 3rd-party ressources only, so LocalStorage isn't our immediate concern.
I added a simple logging catch block around the failing lines. Further error handling may be necessary to ensure proper functionality in situations where LocalStorage inspection is required. 

I don't really understand _why_ this happens, but I'm willing to help if you have any idea.

### CODE REVIEW

**Comment by rriemann-eu** [comment]
Dear @corrupt,

thank you for your contribution in code. I would like to better understand why the error occurs. If you can provide me a testcase either here or to my work mail (firstname DOT lastname AT edps.europa.eu), I can look into it.

**Comment by corrupt** [comment]
Unfortunately I can't reliable reproduce the error. However, here's the trace from last time it happened:

```
(node:3301346) UnhandledPromiseRejectionWarning: Error: Protocol error (DOMStorage.getDOMStorageItems): Frame not found for the given security origin
    at /home/corrupt/git/website-evidence-collector/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/home/corrupt/git/website-evidence-collector/node_modules/puppeteer/lib/Connection.js:182:12)
    at module.exports.getLocalStorage (/home/corrupt/git/website-evidence-collector/lib/tools.js:40:35)
    at runMicrotasks (<anonymous>)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/corrupt/git/website-evidence-collector/website-evidence-collector.js:370:20
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3301346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3301346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The script was invoked like this (you can leave out the `--browser-profile` parameter, though I submitted a pull request for that earlier):
```
website-evidence-collector https://www.abendblatt.de --quiet --html --overwrite --testssl --browser-profile=/home/corrupt/00_PROJECTS/Website Evidence Collector/abendblatt.de/chromium-profile -f https://abendblatt.de -t abendblatt.de -m 250 -- --no-sandbox
```

**Comment by rriemann** [comment]
Thanks for the stack trace. I will try some debugging as follows:

- checkout the WEC source in a folder
- do npm install in this folder
- run `node --inspect-brk website-evidence-collector.js --overwrite -m 250 https://$DOMAIN`
- open chromium and navigate to `chrome://inspect`
- find the debugging session, enable *pause on exception* and potentially some more breakpoints and unpause the debugger
- hope to find something useful

**Comment by corrupt** [comment]
That's a nice trick I didn't know about 😀

Caught it again. Is there any more meaningful way to share this than a screenshot?

Screenshot from 2020-08-26 13-09-33

**Comment by rriemann** [comment]
I have put the fix into tools.js. You can see the summary at https://github.com/EU-EDPS/website-evidence-collector/pull/35/files .

For me, I could scan the journal website with `-m 250` without the script breaking. The file `local-storage.yml` has like 878 lines and I am sure a part of the data are required for assessments.

I wait for your thumb up and merge this then into master.

**Comment by rriemann-eu** [comment]
I have put the fix into tools.js. You can see the summary at https://github.com/EU-EDPS/website-evidence-collector/pull/35/files .

For me, I could scan the journal website with -m 250 without the script breaking. The file local-storage.yml has like 878 lines and I am sure a part of the data are required for assessments.

I wait for your thumb up and merge this then into master.

**Comment by corrupt** [comment]
Had WEC do two 250-page runs with your changes applied and the debugger attachted. No issues here :)

**Comment by rriemann-eu** [comment]
merged to master in 615e4b2061e43e57309a51894dc4ba34c8e5eb13

**Pull request closed without merging**
