### PR TITLE
Prevent a crash when handling specific links (SVG)

### PR DESCRIPTION
**Pull request by fmarquis**
We are using your great tool to check some of our sites, and one of them generates an error. 
This website is using a SVG map with links where the href attribute is not a string, but a SVGAnimatedString object (which don't have a split method) 
My proposition is to simply apply a toString() on the href for now (It will give us a string "[object SVGAElement]", which will be filtered out just after because it does not start with "http") 
A better solution could be to fully manage this kind of link, retrieving the correct href if you prefer, but it may be complicated as this kind of object can have two values (baseVal and animVal)... 
Anyway, thanks for your work, we will probably send some PR as soon as we are ready !

### CODE REVIEW

**Comment by rriemann** [comment]
Thank you @fmarquis  for raising this issue. To get a better idea of the problem, can you post how the html code of such a link looks like?

**Comment by fmarquis** [comment]
Hello Robert,
Of course, should have done that already, my bad.
The page is https://passion-aquitaine.ouest-france.fr/ and you can see a SVG map on the right if you scroll down.
Passion Aquitaine - SVG map
Here is a screenshot of the page and its representation in Chrome, showing the href property.
Thanks

**Comment by rriemann** [comment]
Isn't there a way to obtain the value "/nouvelle-aquitaine/dordogne/" or even an absolute link?

**Comment by fmarquis** [comment]
Hi and sorry for the delay
I looked into the possibility of managing this kind of links, but it is not straightforward : a classical link with a relative "href" is automatically returned as an absolute URL by the browser, but it is not the case with a SVGAElement. So reading its "baseVal" attribute may return a relative URL, which we will have to detect and transform into an absolute one for the following code to run succesfully.
And even with this, we will also need to adjust some other things, like inner_text and inner_html which doesn't work with SVGAElement...
So I'm not sure it's worth the cost
What do you think ?

**Comment by rriemann** [comment]
I agree that this sounds very complicated. Should we then instead print warnings to the log that the page may contain external links in SVGs?

**Comment by fmarquis** [comment]
Good idea, I've updated the code to log a warning when encountering SVG links.
Note : as this code is executed in the context of the page itself (via page.evaluate) and not directly in the context of Website Evidence Collector, I can't use the application logger, only the console.

**Comment by rriemann** [comment]
@fmarquis can you please check if this version works for you before I merge with master?

**Comment by fmarquis** [comment]
Hi @rriemann, this version is working fine, with and without SVG links
Thank you

**Comment by fmarquis** [comment]
just a remark : the new version doesn't remove duplicated links any more, so it can return the same link twice now
I can put back this logic if you want

**Comment by rriemann** [comment]
I just pushed a fix. I hope it does the job.

**Pull request merged**
