### PR TITLE
Page source parameter

### PR DESCRIPTION
**Pull request by elisaifutdinova**
Could we add some functionality for storing a page source as well, please? 🙏  My proposal is in the PR, that is a very quick solution.

### CODE REVIEW

**Comment by rriemann-eu** [comment]
Dear @elisaifutdinova,

thank you for your proposal and your pull request.

The source code of the html file as received is already stored in the har file `requests.har`. This file can be opened in the developer toolbar network tab of Firefox/Chrome per drag'n'drop or with tools such as https://stedolan.github.io/jq/manual/ .

If you think that this is not accessible, we could also save it by default – usually, the files are not that big – and not create a command line option for it.

What's your view?

**Comment by elisaifutdinova** [comment]
Hm 🤔 I've just looked at it, could you please navigate me to the html source code of the page in `requests.har`?

**Comment by elisaifutdinova** [comment]
My view is that there are two ways: WEC should store page source by default or we should describe how to get page source in docs. The first option seems more straightforward. I mean WEC already stores screenshots.

**Comment by rriemann-eu** [comment]
integrated with https://github.com/EU-EDPS/website-evidence-collector/commit/8e19e945243c4a82b63ebf08d7384d96a62cf7a4. I also mentioned this contribution in the README.md

Thank you for the proposal.

**Pull request closed without merging**
